import 'whatwg-fetch'
import 'core-js/features/promise'
import 'core-js/features/set'
import 'core-js/features/map'
import 'core-js/features/array'
import 'core-js/features/object'
import 'core-js/features/string'
